[package]
authors = ["anderejd <rajder@gmail.com>"]
description = "TODO: Write description"
edition = "2018"
license = "Apache-2.0/MIT"
name = "cargo-geiger-serde"
version = "0.1.0"

[dependencies]
semver = "0.11.0"
serde = { version = "1.0.116", features = ["derive"] }
url = { version = "2.1.1", features = ["serde"] }
