[package]
name = "geiger"
description = "Some library parts of cargo-geiger, decoupled from cargo."
version = "0.4.5"
edition = "2018"
authors = ["anderejd <rajder@gmail.com>"]
repository = "https://github.com/rust-secure-code/cargo-geiger"
readme = "README.md"
keywords = ["unsafe"]
categories = ["development-tools", "parsing"]
license = "Apache-2.0/MIT"

[badges]
maintenance = { status = "experimental" }

[dependencies]
cargo-geiger-serde = { path = "../cargo-geiger-serde", version = "0.1.0" }
syn = { version = "1.0.34", features = ["parsing", "printing", "clone-impls", "full", "extra-traits", "visit"] }
proc-macro2 = "1.0.18"

[dev-dependencies]
rstest = "0.6.4"
tempfile = "3.1.0"
